"$schema" = 'https://starship.rs/config-schema.json'

format = """
[ ](fg:color_fg0 bg:color_bg0)\
[](fg:color_bg0 bg:color_red)\
$username\
[](bg:color_bg3 fg:color_red)\
$directory\
[](fg:color_bg3 bg:color_bg3)\
$git_branch\
[](fg:color_bg3)\
$character"""

palette = 'nord'

[palettes.nord]
color_fg0 = '#D8DEE9'  # Snow white
color_bg0 = '#2E3440'  # Dark gray
color_bg1 = '#3B4252'  # Medium gray
color_bg3 = '#4C566A'  # Darker gray
color_blue = '#88C0D0'  # Light blue
color_aqua = '#81A1C1'  # Aqua blue
color_green = '#c1932d'  # Prompt color
color_orange = '#D19A66'  # Light orange
color_purple = '#B48EAD'  # Light purple
color_red = '#BF616A'  # Light red
color_yellow = '#EBCB8B'  # Light yellow
color_uname = '#1A1F24'  # Uname color

[os]
disabled = true
style_root = "bg:color_red fg:color_fg0"
format = '[$symbol ]($style)'

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:color_red fg:color_bg0"
style_root = "bg:color_red fg:color_bg0"
format = '[ $user ]($style)'

[directory]
style = "bg:color_bg3 fg:color_fg0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "\uf15c"
"Downloads" = "\uf409"
"Music" = "\uec1b"
"Pictures" = "\uf03e"
format = '[$symbol]($style)'

[git_branch]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_aqua)]($style)'

[git_status]
style = "bg:color_aqua"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_aqua)]($style)'

[nodejs]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[c]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[rust]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[golang]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[php]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[java]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[kotlin]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[haskell]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[python]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:color_fg0 bg:color_bg3)]($style)'

[conda]
style = "bg:color_bg3"
format = '[[ $symbol( $environment) ](fg:color_fg0 bg:color_bg3)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg0 bg:color_bg1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[ \$](bold fg:color_green)'
error_symbol = '[ \$](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
